java -jar zipkin-server-2.23.9-exec.jar \
--zipkin.collector.rabbitmq.addresses=192.168.3.122:5672 \
--zipkin.collector.rabbitmq.username=admin \
--zipkin.collector.rabbitmq.password=admin \
--zipkin.collector.rabbitmq.queue=zipkin \
--zipkin.storage.type=mysql \
--zipkin.storage.mysql.host=192.168.3.122 \
--zipkin.storage.mysql.port=3306 \
--zipkin.storage.mysql.username=root \
--zipkin.storage.mysql.password=Root@123 \
--zipkin.storage.mysql.db=zipkin